<?php

// @codingStandardsIgnoreFile
?>
<div id="checkout" data-bind="scope:'checkout'" class="checkout-container glc">
    <div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
        <div class="loader">
            <img src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
                 alt="<?php /* @escapeNotVerified */ echo __('Loading...'); ?>"
                 style="position: absolute;">
        </div>
    </div>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#checkout": {
                "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
            }
        }
    </script>
    <script>
        window.checkoutConfig = <?php /* @escapeNotVerified */ echo json_encode($block->getCheckoutConfig(), JSON_HEX_TAG); ?>;
        // Create aliases for customer.js model from customer module
        window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
        window.customerData = window.checkoutConfig.customerData;
    </script>
    <script>
        require([
            'mage/url',
            'Magento_Ui/js/block-loader'
        ], function(url, blockLoader) {
            blockLoader("<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>");
            return url.setBaseUrl('<?php /* @escapeNotVerified */ echo $block->getBaseUrl();?>');
        })
    </script>
    <script>
        require(["jquery"], function($){

            $(document).on('touchstart', function(e){
                var container = $(".field-tooltip");

                if (!container.is(e.target) && container.has(e.target).length === 0){
                    container.removeClass("_active");
                }
            });

        });
    </script>
</div>


<?php

if ($block->isRegistrationPopupAvailable()) { ?>
    <div id="checkout-registration-popup" style="display: none;">
        <a class="registration-popup-link" style="display: none;">register</a>
        <?php echo $block->getChildHtml('customer_form_register_on_checkout'); ?>
        <?php echo $block->getChildHtml('social_network_on_checkout_registration_popup'); ?>
    </div>
    <script type="text/x-magento-init">
    {
        ".registration-popup-link": {
            "GoMage_LightCheckout/js/popup": {}
        }
    }
    </script>
    <?php
}
?>
